import uns.ac.rs.model.Bill;
import uns.ac.rs.model.BillDiscount;
import uns.ac.rs.model.Item;
import uns.ac.rs.model.ItemDiscount
import uns.ac.rs.model.enums.DiscountType;
import uns.ac.rs.model.AllBills;
import uns.ac.rs.model.Article
import uns.ac.rs.model.ArticleCategory;
import uns.ac.rs.model.User;
import uns.ac.rs.model.Event;
import java.util.List
import uns.ac.rs.model.enums.StatusOfArticle;


rule "more then 20"
    lock-on-active true
    salience 12

    when
        $bill : Bill($items : items)
        $item : Item(article.articleCategory.articleCategory == null || article.articleCategory.articleCategory.title.equals("broad_consumption") == false, quantity > 20) from $items
    then
        System.out.println("Drools role more then 20");
        $item.getItemDiscounts().add(new ItemDiscount($bill, $item, 10.0, DiscountType.BASIC, "More then 20 articles"));
        update($item);
end

rule "more then 5 pc, lap top or tv"
    lock-on-active true
    salience 11

    when
        $bill : Bill($items : items)
        $item : Item(article.articleCategory.title in ("tvs","computers","laptops"), quantity > 5) from $items
    then
        System.out.println("Drools role more then 5 Tech");
        $item.getItemDiscounts().add(new ItemDiscount($bill, $item, 5.0, DiscountType.BASIC, "More then 5 PCs, Lap Tops or TVs"));
        update($item)
end

rule "more than 5000din and broad consumption category"
    lock-on-active true
    salience 10

    when
        $bill : Bill($items : items)
        $item : Item(article.articleCategory.articleCategory != null, article.articleCategory.articleCategory.title.equals("broad_consumption") == true , currentPrice > 5000) from $items
    then
       System.out.println("Drools role more than 5000din of broad consumption products");
       $item.getItemDiscounts().add(new ItemDiscount($bill, $item, 7.0, DiscountType.BASIC, "More than 5000din of broad consumption products"));
       update($item)
end


rule "article purchased 15 days ago"
    lock-on-active true
    salience 8

    when
        $bill : Bill($items : items)
        AllBills($b: bills)
        $bills: Bill(($bill.date.getTime() - date.getTime()) / (1000*60*60*24) < 15, $old: items) from $b
        $oldItems: Item($article: article) from $old
        $buyedArt: Article() from $article

        $it: Item(article.id == $buyedArt.id, $bill.getFactVariable() == 0) from $items

    then
        System.out.println("Drools role: article purchased 15 days ago!");
        $it.getItemDiscounts().add(new ItemDiscount($bill, $it, 2.0, DiscountType.ADVANCED, "Article purchased 15 days ago"));
        modify($bill){
            setFactVariable(1)
        }
end

rule "article purchased from category in last 30 days"
    lock-on-active true
    salience 7

    when
        $bill : Bill($items : items)
        AllBills($b: bills)
        $bills: Bill(($bill.date.getTime() - date.getTime()) / (1000*60*60*24) < 15, $old: items) from $b
        $oldItems: Item($article: article) from $old
        $buyedArt: Article() from $article

        $it: Item(article.articleCategory.id == $buyedArt.articleCategory.id, $bill.getFactVariable() == 0 || $bill.getFactVariable() == 1) from $items

    then
        System.out.println("Drools role: article purchased from category in last 30 days!");
        $it.getItemDiscounts().add(new ItemDiscount($bill, $it, 1.0, DiscountType.ADVANCED, "Article purchased from category in last 30 days" ));
        modify($bill){
            setFactVariable(2)
        }
end

rule "events"
    lock-on-active true
    salience 4

    when
        $bill : Bill($items: items, $date : date)
        $event : Event(starts < $date, $date < ends, $categories: categories)
        $category: ArticleCategory() from $categories
        $item: Item(article.articleCategory.id == $category.id) from $items
    then
        System.out.println("Drools role: Events!");
        $item.getItemDiscounts().add(new ItemDiscount($bill, $item, $event.getDiscount(), DiscountType.ADVANCED, "Active Events"));

end


